# file: hostname/tasks/main.yml

- name: Hostname | Update the hostname (pt. 1) - hostname cmd
  hostname:
    name: "{% if inventory_hostname_extended is defined %}{{ inventory_hostname_extended }}{% else %}{{ inventory_hostname_short }}{% endif %}"

- name: Hostname | Update the hostname (pt. 2) - (/etc/hostname)
  copy:
    content: "{% if inventory_hostname_extended is defined %}{{ inventory_hostname_extended }}{% else %}{{ inventory_hostname_short }}{% endif %}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: Hostname | Update the hostname (pt. 3) - (/etc/hosts)
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1{{'\t'}}localhost{{'\t'}}{{inventory_hostname}}{% if inventory_hostname_extended is defined %}{{'\t'}}{{inventory_hostname_extended}}{% else %}{% if inventory_hostname != inventory_hostname_short %}{{'\t'}}{{inventory_hostname_short}}{% endif %}{% endif %}"
    state: present
